# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for InfluxDB MCP Server
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --production

# Copy source code
COPY src ./src

# Use lightweight non-root user (optional)
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# USER appuser

# Expose the default HTTP port
EXPOSE 3000

# Entrypoint for MCP server (using HTTP transport by default)
ENTRYPOINT ["node", "src/index.js", "--http"]
